---
kind: Service
apiVersion: v1
metadata:
  name: exampleservice
spec:
  selector:
    app: myapp
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 8081
      # Port to forward to inside the pod
      targetPort: 8080
      # Port accessible outside cluster
      nodePort: 30003
  type: LoadBalancer


---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: myappdeployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: bitfroest/euro2016
          imagePullPolicy: Always
          env:
          - name: DB_HOST
            value: "postgresql"
          - name: DB_USER
            value: "postgres"
          - name: DB_PASSWORD
            value: "Test1234"
          - name: DB_NAME
            value: "soccer"
          - name: SESSION_SECRET
            value: "blabla"
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 100m
              memory: 2Gi
            requests:
              cpu: 25m
              memory: 300Mi

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: myapp-agent
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: myappdeployment
  minReplicas: 1
  maxReplicas: 6
  targetCPUUtilizationPercentage: 40
status:
  currentReplicas: 1
  desiredReplicas: 1
